name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: gcc -O3 -mavx -pthread -o gpt2 gpt2_opt.c -lm

    - name: Run
      run: ./gpt2
